# Generated by Django 5.0 on 2023-12-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('idAdministrateur', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'db_table': 'Administrateur',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=45)),
                ('Contact', models.CharField(max_length=45)),
                ('Statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('idFournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=45)),
                ('Contact', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'Fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('idMArque', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'db_table': 'Marque',
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('idHistorique', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Achat', models.CharField(max_length=45)),
                ('Designation', models.CharField(max_length=45)),
                ('Montant_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Montant_Paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Montant_Restant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'db_table': 'Historique',
            },
        ),
        migrations.CreateModel(
            name='Pneu',
            fields=[
                ('idPneu', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=45)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stockage', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fournisseur')),
                ('Marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.marque')),
            ],
            options={
                'verbose_name': 'Pneu',
                'verbose_name_plural': 'Pneus',
                'db_table': 'Pneu',
            },
        ),
        migrations.CreateModel(
            name='PneuHistorique',
            fields=[
                ('idPneuHistorique', models.AutoField(primary_key=True, serialize=False)),
                ('Historique_idHistorique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.historique')),
                ('Pneu_Numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pneu')),
            ],
            options={
                'verbose_name': 'PneuHistorique',
                'verbose_name_plural': 'PneuHistorique',
                'db_table': 'PneuHistorique',
            },
        ),
    ]
