# Generated by Django 5.0 on 2023-12-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_numero_alter_pneu_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('idTransaction', models.AutoField(primary_key=True, serialize=False)),
                ('Details', models.CharField(max_length=45)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stockage', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fournisseur')),
                ('Marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.marque')),
                ('Numero', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.numero')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'Transaction',
            },
        ),
    ]
