# Generated by Django 5.0 on 2024-01-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('idNature', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=45)),
            ],
            options={
                'verbose_name': 'Nature',
                'verbose_name_plural': 'Natures',
                'db_table': 'Nature',
            },
        ),
    ]
