# Generated by Django 5.0 on 2024-01-03 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_nature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneuhistorique',
            options={},
        ),
        migrations.AlterModelTable(
            name='pneuhistorique',
            table=None,
        ),
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('idAccessoire', models.AutoField(primary_key=True, serialize=False)),
                ('Details', models.CharField(max_length=45)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stockage', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fournisseur')),
                ('Marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.marque')),
                ('Numero', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.numero')),
            ],
            options={
                'verbose_name': 'Accessoire',
                'verbose_name_plural': 'Accessoires',
                'db_table': 'Accessoire',
            },
        ),
        migrations.CreateModel(
            name='AccessoireHistorique',
            fields=[
                ('idAccessoireHistorique', models.AutoField(primary_key=True, serialize=False)),
                ('Accesoire_Numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pneu')),
                ('Historique_idHistorique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.historique')),
            ],
            options={
                'verbose_name': 'AccessoireHistorique',
                'verbose_name_plural': 'AccessoireHistorique',
                'db_table': 'AccessoireHistorique',
            },
        ),
        migrations.CreateModel(
            name='Batterie',
            fields=[
                ('idBatterie', models.AutoField(primary_key=True, serialize=False)),
                ('Details', models.CharField(max_length=45)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stockage', models.CharField(max_length=45)),
                ('Quantite', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fournisseur')),
                ('Marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.marque')),
                ('Numero', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.numero')),
            ],
            options={
                'verbose_name': 'Batterie',
                'verbose_name_plural': 'Batteries',
                'db_table': 'Batterie',
            },
        ),
        migrations.CreateModel(
            name='BatterieHistorique',
            fields=[
                ('idBatterieHistorique', models.AutoField(primary_key=True, serialize=False)),
                ('Batterie_Numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pneu')),
                ('Historique_idHistorique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.historique')),
            ],
            options={
                'verbose_name': 'BatterieHistorique',
                'verbose_name_plural': 'BatterieHistorique',
                'db_table': 'BatterieHistorique',
            },
        ),
    ]
