# Generated by Django 5.0 on 2024-01-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_pneuhistorique_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pneuhistorique',
            options={'verbose_name': 'PneuHistorique', 'verbose_name_plural': 'PneuHistorique'},
        ),
        migrations.AlterModelTable(
            name='pneuhistorique',
            table='PneuHistorique',
        ),
    ]
