# Generated by Django 5.0 on 2024-01-03 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_pneuhistorique_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Nature',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.nature'),
        ),
    ]
