# Generated by Django 5.0 on 2024-01-03 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_transaction_nature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessoirehistorique',
            options={},
        ),
        migrations.AlterField(
            model_name='accessoirehistorique',
            name='Accesoire_Numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.accessoire'),
        ),
        migrations.AlterField(
            model_name='batteriehistorique',
            name='Batterie_Numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.batterie'),
        ),
        migrations.AlterModelTable(
            name='accessoirehistorique',
            table=None,
        ),
    ]
