# Generated by Django 5.0 on 2024-01-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_accessoirehistorique_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessoirehistorique',
            options={'verbose_name': 'AccessoireHistorique', 'verbose_name_plural': 'AccessoireHistorique'},
        ),
        migrations.AlterModelTable(
            name='accessoirehistorique',
            table='AccessoireHistorique',
        ),
    ]
